window.FIRMWARE_CATALOG = [
  { brand: 'Motorola', name: 'Moto Edge S Pro / S-PRO', model: 'XT2153-1', code: 'pstar_retcn', region: 'CMCC', url: 'https://mirrors-obs-1.lolinet.com/firmware/lenomola/2021/pstar_retcn/official/CMCC/' },
  { brand: 'Motorola', name: '摩托罗拉 Edge S30', model: 'XT2175', code: 'xpeng_retcn', region: 'RETCN', url: 'https://mirrors-obs-1.lolinet.com/firmware/lenomola/2021/xpeng_retcn/official/RETCN/' },
  { brand: 'Motorola', name: 'Moto G71s', model: 'G71s', code: 'corfur_retcn', region: 'CTCN', url: 'https://mirrors-obs-1.lolinet.com/firmware/lenomola/2021/corfur_retcn/official/CTCN/' },
  { brand: 'Motorola', name: 'Moto X30 Pro', model: 'XT2241-1', code: 'eqs_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2022/eqs_retcn/official/RETCN/' },
  { brand: 'Motorola', name: 'Moto Razr 40 Ultra', model: 'Razr 40 Ultra / Razr+', code: 'zeekr_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2023/zeekr_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Razr 40', model: 'Razr 40', code: 'lynkco_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2023/lynkco_retcn/official/' },
  { brand: 'Motorola', name: 'Moto G53 / G 5G', model: 'Moto G 2023', code: 'penang_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2023/penang_retcn/official/' },
  { brand: 'Motorola', name: 'Moto G54', model: 'Moto G 2023', code: 'cancunf_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2023/cancunf_retcn/official/' },
  { brand: 'Motorola', name: 'Moto G34', model: 'Moto G 2023', code: 'fogos_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2023/fogos_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Razr 50 Ultra', model: 'Razr 50 Ultra', code: 'aito_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/aito_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Razr 50', model: 'Razr 50', code: 'arcfox_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/arcfox_retcn/official/' },
  { brand: 'Motorola', name: 'Moto X50 Ultra', model: 'XT2401 / X50 Ultra', code: 'ctwo_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/ctwo_retcn/official/RETCN/' },
  { brand: 'Motorola', name: 'Moto S50 Neo / Edge 50 Fusion', model: '2024', code: 'paros_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/paros_retcn/official/' },
  { brand: 'Motorola', name: 'Moto G85 / S50', model: '2024', code: 'taipei_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/taipei_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Edge 50 Pro / X50', model: '2024', code: 'vienna_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/vienna_retcn/official/' },
  { brand: 'Motorola', name: 'Moto G 2024 / MALMO', model: 'XT2427-4 / C34.49-29-1', code: 'malmo_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2024/malmo_retcn/official/RETCN/' },
  { brand: 'Motorola', name: 'Moto Razr 60 Ultra', model: '2025', code: 'aito25_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/aito25_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Razr 60', model: '2025', code: 'arcfox25_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/arcfox25_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Edge 60 Pro', model: '2025', code: 'cybert_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/cybert_retcn/official/' },
  { brand: 'Motorola', name: 'Moto Edge 60', model: '2025', code: 'leap_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/leap_retcn/official/' },
  { brand: 'Motorola', name: 'Moto G 2025', model: '2025', code: 'nice_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/nice_retcn/official/' },
  { brand: 'Motorola', name: 'Moto 2025 / PORTOV', model: '2025', code: 'portov_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/portov_retcn/official/' },
  { brand: 'Motorola', name: 'Moto 2025 / ROADSTR', model: '2025', code: 'roadstr_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/roadstr_retcn/official/' },
  { brand: 'Motorola', name: 'Moto 2025 / SCOUT', model: '2025', code: 'scout_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2025/scout_retcn/official/' },
  { brand: 'Motorola', name: 'Moto 2026 / MUMBA', model: '2026', code: 'mumba_retcn', region: 'RETCN', url: 'https://mirrors.lolinet.com/firmware/lenomola/2026/mumba_retcn/official/' },
  { brand: 'Lenovo', name: '联想拯救者 Y70', model: 'L71091', code: 'L71091', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2022/l71091/' },
  { brand: 'Lenovo', name: '联想拯救者 Y90', model: 'L71061', code: 'L71061', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2022/l71061/' },
  { brand: 'Lenovo', name: '联想拯救者 Y700', model: 'Y700 2022', code: 'Legion_Y700', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2022/Legion_Y700/' },
  { brand: 'Lenovo', name: '联想拯救者 Y700 2023', model: 'Y700 2023', code: 'Y700_2023', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2023/Y700_2023/' },
  { brand: 'Lenovo', name: '联想拯救者 Y700 2025', model: 'Y700 2025', code: 'Y700_2025', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2024/Y700_2025/' },
  { brand: 'Lenovo', name: '联想拯救者 Y700 4th Gen', model: 'Y700 4th Gen', code: 'Y700_4th_Gen', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2025/Y700_4th_Gen/' },
  { brand: 'Lenovo', name: '联想 Y70 2026', model: 'Legion Y70 2026', code: 'Legion_Y70_2026', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2026/Legion_Y70_2026/' },
  { brand: 'Lenovo', name: '小新 Pad Pro 2022 骁龙版', model: 'Xiaoxin Pad Pro 2022', code: 'Xiaoxin_Pad_Pro_2022_Snapdragon', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2022/Xiaoxin_Pad_Pro_2022_Snapdragon/' },
  { brand: 'Lenovo', name: '小新 Pad Pro 12.7 2023', model: 'Xiaoxin Pad Pro 12.7', code: 'Xiaoxin_Pad_Pro_12.7_2023', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2023/Xiaoxin_Pad_Pro_12.7_2023/' },
  { brand: 'Lenovo', name: '小新 Pad 2024', model: 'Xiaoxin Pad 2024', code: 'Xiaoxin_Pad_2024', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2024/Xiaoxin_Pad_2024/' },
  { brand: 'Lenovo', name: '联想 Yoga Pad Pro 2025', model: 'Yoga Pad Pro 2025', code: 'Yoga_Pad_Pro_2025', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2024/Yoga_Pad_Pro_2025/' },
  { brand: 'Lenovo', name: '联想 Yoga Tab 2025', model: 'Yoga Tab 2025', code: 'Yoga_Tab_2025', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2025/Yoga_Tab_2025/' },
  { brand: 'Lenovo', name: '联想 Tab P12 2023', model: 'Tab P12', code: 'Tab_P12_2023', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2023/Tab_P12_2023/' },
  { brand: 'Lenovo', name: '联想 Tab P11 Pro 2nd Gen', model: 'Tab P11 Pro 2nd Gen', code: 'Tab_P11_Pro_2nd_Gen', region: 'CN', url: 'https://mirrors.lolinet.com/firmware/lenowow/2022/Tab_P11_Pro_2nd_Gen/' }
];
